site_name: Programming 4
copyright: Bart Barnard
site_author: Bart Barnard
site_description: 'Exercises for the module Programming 4 of the master Data Science for Life Science'
site_url: 'https://bioinf.nl/~bbarnard/programming4'
use_directory_urls: false

theme:
  name: readthedocs
  palette:
    primary: 'blue grey'
    accent: 'orange'
  icon:
    logo: 'material/library'
  language: 'nl'
  include_sidebar: false
  highlightjs: true

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.codehilite:
      guess_lang: False
      linenums: True
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

extra_javascript:
  - js/imgs.js
  - js/matjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
#  - with-pdf
  - search
  - mknotebooks:
      execute: false

nav:
  - Introduction: 'index.md'
  - Multiple Class Interaction: 'week1.1.md'
  - SOLID and design patterns: 'week1.2.md'
  - List comprehensions and generators: 'week1.4.md'
  - Parallelisation: 'week2.2.md'